# Generated by Django 2.2.4 on 2019-09-28 15:23

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_match_players'),
        ('players', '0002_auto_20190908_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches',
            field=modelcluster.fields.ParentalManyToManyField(related_name='players', to='matches.Match', verbose_name='matches'),
        ),
    ]
