# Generated by Django 2.2.4 on 2019-09-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
    ]
