#!/bin/bash
PROJECT_SLUG=project
USER=django

HOME=/home/$USER
DIR=$HOME/$PROJECT_SLUG
USER=$USER
GROUP=$USER
WORKERS=3
BIND=unix:$HOME/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=config.settings.production
DJANGO_WSGI_MODULE=config.wsgi
LOG_LEVEL=error
VIRTUALENV_PATH=$HOME/.virtualenvs/$PROJECT_SLUG/bin

cd $DIR
source $VIRTUALENV_PATH/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec $VIRTUALENV_PATH/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $PROJECT_SLUG \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-