"""
Generated by 'django-admin startproject' using Django 1.11.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from .defaults import *

INSTALLED_APPS += [
    "core",
    "users",
    "matches",
    "goals",
    "players",
]

TEMPLATES[0]['OPTIONS']['context_processors'] += [
    'core.context_processors.project',
]

# CRISPY FORMS
# ------------------------------------------------------------------------------
# https://django-crispy-forms.readthedocs.io/en/latest/install.html#template-packs

INSTALLED_APPS = ['crispy_forms'] + INSTALLED_APPS
CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_FAIL_SILENTLY = not DEBUG

INCLUDE_AUTH_URLS = False
INCLUDE_REGISTER_URL = False # using custom View
REGISTRATION_ADMINS = ADMINS

# DJANGO REST FRAMEWORK
# ------------------------------------------------------------------------------
# https://www.django-rest-framework.org

INSTALLED_APPS += ['rest_framework']
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAdminUser',
    ),
}

# YET ANOTHER SWAGGER GENERATOR
# ------------------------------------------------------------------------------
# https://drf-yasg.readthedocs.io

INSTALLED_APPS += ['drf_yasg']
