# Generated by Django 2.2.4 on 2019-09-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20190908_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
