# Generated by Django 2.2.4 on 2019-09-21 12:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['sort_order'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='match',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='matches.Match', verbose_name='match'),
        ),
    ]
