# Generated by Django 2.2.7 on 2019-11-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20190921_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['match'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='matches.Match', verbose_name='match'),
        ),
    ]
