# Generated by Django 2.2.4 on 2019-09-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20190908_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent_goals',
            field=models.PositiveIntegerField(null=True, verbose_name='opponent goals'),
        ),
    ]
