# Generated by Django 2.2.4 on 2019-09-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
    ]
