# Generated by Django 2.2.4 on 2019-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_matches'),
        ('matches', '0005_remove_match_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', to='players.Player', verbose_name='players'),
        ),
    ]
